### ISSUE TITLE
How to add a parameterized permission 

### ISSUE THREAD

**Issue by lkngtn** [1Hive/token-oracle#2]
In order for this to be used we need to be able to add a parameterized permission. I believe we can do that in the template currently, but it would also be good to be able to do it through the CLI and/or the Web Client. Adding related issues from those repos here for reference. 
 
Related issue in the CLI: https://github.com/aragon/aragon-cli/issues/407 
Related issue in the Web Client: https://github.com/aragon/aragon/issues/821 , https://github.com/aragon/aragon/issues/1071

**Comment by fabriziovigevani** [comment]
Yes, it can be done through the template and can also be done through a truffle script. 

Agree that it would be really helpful to have it implemented in the CLI. 

@0xGabi do you think this could be done soon? I could get my hands on it as well 👍

**Comment by 0xGabi** [comment]
I think we have good news on this front, I asked help a couple of days ago to @macor161 with this one and he was making progress. For sure he can tell you guys how far we are 💪

**Comment by macor161** [comment]
Hi! Yes I just started working on this for the CLI. I will probably be able to submit a pull request by the end of next week or the week after.

**Comment by macor161** [comment]
I'm finishing up the feature on the CLI today: https://github.com/aragon/aragon-cli/pull/807
What do you guys think of the syntax?
Any suggestion, comment or questions are welcome.

**Comment by 0xGabi** [comment]
@fabriziovigevani @willjgriff @lkngtn ☝️

**Comment by lkngtn** [comment]
Syntax seems intuitive to me, atleast as intuitive as acl params can be 😂

**Comment by fabriziovigevani** [comment]
Just gave it a test today and works like a charm! 

I think the syntax maps perfect with the acl params documentation.
Thank you @macor161 !

Refactored script [here](https://github.com/1Hive/time-lock-app/pull/62) which will use this new feature
